esphome:
  name: x500
  friendly_name: vacuum XY

esp8266:
  board: esp12e

external_components:
  - source: github://<DEIN-GITHUB-USERNAME>/x500_vacuum
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

ota:
  platform: esphome
  password: !secret ota_password

api:
  encryption:
    key: !secret api_password

uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 115200

x500_vacuum:
  uart_id: uart_bus
  rawstate_id: rawstate
  vacstate_id: vacstate
  errorstate_id: errorstate
  batdata_id: batdata
